config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:show] do
    resources :tweets, only: [:index, :show]
    resources :follows, only: [:index]
    resources :followers, only: [:index]
    resources :likes, only: [:index]
  end

  resource :account, only: [:new, :create]
  resource :search, only: [:show]

  namespace :my do
    get '/', to: redirect('/my/home')
    resource :home, only: [:show]
    resource :account, only: [:edit, :update, :destroy]
    resources :tweets, only: [:new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
    resources :follows, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]

  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_many :likes
  belongs_to :user
  
  validates :text, presence: true

  def self.search(search)
  	where("lower(text) LIKE ?", "%#{search}%")
  end
end

app/controllers/my/tweets_controller.rb
class My::TweetsController < My::BaseController
  def new
    
  end

  def create
    @tweet = current_user.tweets.create(tweet_params)

    if @tweet.persisted?
      flash[:success] = 'Your Tweet was posted!'
      redirect_to current_user
    else
      flash[:warning] = 'Please type a message to tweet!'
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to new_my_tweet_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.find(params[:user_id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = User.find(params[:user_id])
    @people_liked_id = Like.where(tweet_id: params[:id]).order('created_at DESC').collect { |like| like.user_id }
    @people_liked = User.all.where(id: @people_liked_id)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/index.html.slim
h1 Show all tweets by this user (in progress)

= params[:user_id]

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= form_for :tweet, url: tweets_path do |f| %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tweets/show.html.slim
.col-xs-offset-3.col-xs-6
  .panel.panel-info
    .panel-heading
      h3 Tweet
    .panel-body
      .media
        .media-left
          = link_to user_path(@tweet.user_id)
            = image_tag @user.avatar.thumb.url, class: 'img-rounded avatar-thumb'
        .media-body
          .username
            = link_to @user.username, user_path(@user.id)
          = link_to @tweet.text, user_tweet_path(@user.id, @tweet.id)
          .timestamp
            p = @tweet.created_at
          - if current_user.present?
            - if like = @tweet.likes.find_by(user_id: current_user.id)
              = button_to "Unlike!", my_tweet_like_path(@tweet, like), method: :delete, class: "btn btn-danger btn-xs"
            - else
              = button_to "Like!", my_tweet_likes_path(@tweet), method: :post, class: "btn btn-primary btn-xs"
      hr
      h3 People who like this tweet
      hr
      - @people_liked.each do |people|
        .media-left
          = image_tag people.avatar.thumb.url, class: 'img-rounded', height: '64', width: '64'
        .media-body
          p = people.username
        hr