config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:show] do
    resources :tweets, only: [:index, :show]
    resources :follows, only: [:index]
    resources :followers, only: [:index]
    resources :likes, only: [:index]
  end

  resource :account, only: [:new, :create]
  resource :search, only: [:show]

  namespace :my do
    get '/', to: redirect('/my/home')
    resource :home, only: [:show]
    resource :account, only: [:edit, :update, :destroy]
    resources :tweets, only: [:new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
    resources :follows, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]

  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
	belongs_to :followee, foreign_key: 'followee_id', class_name: 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_many :likes
  belongs_to :user
  
  validates :text, presence: true

  def self.search(search)
  	where("lower(text) LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :followers, through: :followee_follows, source: :follower
  has_many :followees, through: :follower_follows, source: :followee
  has_many :followee_follows, foreign_key: :followee_id, class_name: 'Follow' # is a join table
  has_many :follower_follows, foreign_key: :follower_id, class_name: 'Follow' # is a join table

  authenticates_with_sorcery!

  validates :password, length: { minimum: 3}, confirmation: true
  EMAIL_REGEX = /@/
  validates :email, uniqueness: true, presence: true, format: { with: EMAIL_REGEX , multiline: true }, case_sensitive: false
  validates :username, uniqueness: true, presence: true
  validates :name, presence: true

  mount_uploader :avatar, AvatarUploader

  def self.search(search)
  	where("username LIKE ?", "%#{search}%")
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome!'
      login user_params[:email], user_params[:password]
      redirect_to my_home_path
    else
      flash[:error] = 'Your registration was unsuccessful!'
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
	def index
		@user = User.find(params[:user_id])
		@followers = @user.followers
	end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def index
		@user = User.find(params[:user_id])
		@followees = @user.followees
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @tweet_likes_id = Like.where(user_id: params[:user_id]).order('created_at DESC').collect { |like| like.tweet_id }
    @tweets_liked = Tweet.all.where(id: @tweet_likes_id)
    @users_of_tweets_liked = User.all.where(id: @tweets_liked.collect { |tweet| tweet.user_id } )
    @user = User.find(params[:user_id])
  end

end

app/controllers/my/base_controller.rb
class My::BaseController < ApplicationController
  before_action :logged_in

  private
  def logged_in
    if !current_user.present?
      flash[:error] = 'You need to be logged in to view this page.'
      redirect_to log_in_path
    end
  end
end

app/controllers/my/homes_controller.rb
class My::HomesController < My::BaseController
  def show
    @user = current_user
    @followed_users = current_user.followees
    @tweets = Tweet.all.where(user_id: @followed_users.ids).order('created_at DESC').paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/my/likes_controller.rb
class My::LikesController < My::BaseController

  def create
    @like = current_user.likes.create(user_id: current_user.id, tweet_id: params[:tweet_id])
    redirect_to :back
  end

  def destroy
    Like.where(user_id: current_user.id, tweet_id: params[:tweet_id]).destroy_all
    redirect_to :back
  end

end

app/controllers/my/tweets_controller.rb
class My::TweetsController < My::BaseController
  def new
    
  end

  def create
    @tweet = current_user.tweets.create(tweet_params)

    if @tweet.persisted?
      flash[:success] = 'Your Tweet was posted!'
      redirect_to current_user
    else
      flash[:warning] = 'Please type a message to tweet!'
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to new_my_tweet_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def show
		if params[:search]
			@tweets = Tweet.search(params[:search].downcase).order("created_at DESC")
			@users = User.search(params[:search].downcase).order("created_at DESC")
		else
			@tweets = nil
			@users = nil
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user.present?
      redirect_to my_home_path
    end
  end

  def create
    if login(params[:email], params[:password])
      flash[:success] = 'Welcome back!'
      redirect_to my_home_path
    else
      flash.now[:warning] = 'E-mail and/or password is incorrect.'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you!'
    redirect_to log_in_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.find(params[:user_id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = User.find(params[:user_id])
    @people_liked_id = Like.where(tweet_id: params[:id]).order('created_at DESC').collect { |like| like.user_id }
    @people_liked = User.all.where(id: @people_liked_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def show
		@user = User.find(params[:id])
	end
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome!'
      redirect_to new_user_path
    else
    	flash[:error] = 'Your registration was unsuccessful!'
      render 'new'
    end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = 'Profile updated!'
			redirect_to edit_user_path
		else
			flash[:error] = 'Your changes were unsaved'
			render 'edit'
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :birthdate, :description, :location, :avatar)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@tweets = @user.tweets.all.order('created_at DESC').paginate(page: params[:page], per_page: 20)
    
		if current_user
			@me = current_user
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(
        content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
          concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
          concat message 
        end)
    end
    nil
  end
  
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    = link_to "Twitter Clone", root_path, class: "navbar-brand"
    = form_tag search_path, method: :get, class: "navbar-form navbar-left"
      .input-group
        = text_field_tag :search, params[:search], placeholder: "Search for users and tweets", class: "form-control", id: "search-field"
        span.input-group-btn
          = submit_tag "Search", class: "btn btn-default"
    ul.nav.navbar-nav.navbar-right
      li
        = link_to new_my_tweet_path
          span.glyphicon.glyphicon-pencil
          | Tweet
      li.dropdown
        = link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" }
          span.glyphicon.glyphicon-user
          = current_user.name
          span.caret
        ul.dropdown-menu
          li
            = link_to "View Profile", user_path(current_user.id)
          li
            = link_to "Manage Account", edit_my_account_path
          li.divider
          li
            = link_to "Log Out", log_out_path, method: :delete

app/views/shared/_public_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    = link_to "Twitter Clone", root_path, class: "navbar-brand"
    = form_tag search_path, method: :get, class: "navbar-form navbar-left"
      .input-group
        = text_field_tag :search, params[:search], placeholder: "Search for users and tweets", class: "form-control", id: "search-field"
        span.input-group-btn
          = submit_tag "Search", class: "btn btn-default"
    ul.nav.navbar-nav.navbar-right
      li
        = link_to new_account_path
          span.glyphicon.glyphicon-user
          | Create Account
      li
        = link_to log_in_path
          span.glyphicon.glyphicon-log-in
          | Log In

app/views/shared/_user_info.html.slim
.user-info
	.panel.panel-default
		.panel-body
			.text-center
				= image_tag @user.avatar.thumb.url, class: "img-rounded"
				h4 = link_to @user.username, user_path(@user.id), class: "username"
				p = @user.name
				p = @user.email
				- if @me
					- if @me.followees.include?(@user)
						= button_to "Unfollow", my_follow_path(@user.id), class: "btn btn-danger"
					- elsif @me != @user
						= button_to "Follow", my_follows_path(@user.id), class: "btn btn-default"
				br
				.row
					= link_to user_path(@user.id) do
						.col-md-3
							.text-center
								p = @user.tweets.count
								p tweets
					= link_to user_follows_path(@user.id) do
						.col-md-3
							.text-center
								p = @user.followees.count
								p following
					= link_to user_followers_path(@user.id) do
						.col-md-3
							.text-center
								p = @user.followers.count
								p followers
					= link_to user_likes_path(@user.id) do
						.col-md-3
							.text-center
								p = @user.likes.count
								p likes